package frpc

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"sync"
	"time"

	"github.com/frp-cloud-panel/client-panel/internal/config"
	"github.com/frp-cloud-panel/client-panel/internal/api"
)

// Manager FRPC 管理器
type Manager struct {
	cfg        *config.Config
	cmd        *exec.Cmd
	running    bool
	mu         sync.RWMutex
	stopCh     chan struct{}
	statusCh   chan Status
}

// Status FRPC 状态
type Status struct {
	Running bool
	Error   string
}

// NewManager 创建新的 FRPC 管理器
func NewManager(cfg *config.Config) *Manager {
	return &Manager{
		cfg:      cfg,
		stopCh:   make(chan struct{}),
		statusCh: make(chan Status, 1),
	}
}

// Start 启动 FRPC
func (m *Manager) Start() error {
	m.mu.Lock()
	defer m.mu.Unlock()

	if m.running {
		return fmt.Errorf("frpc is already running")
	}

	// 检查配置文件是否存在
	if _, err := os.Stat(m.cfg.FRPC.ConfigPath); os.IsNotExist(err) {
		return fmt.Errorf("config file not found: %s", m.cfg.FRPC.ConfigPath)
	}

	// 创建日志目录
	logDir := filepath.Dir(m.cfg.FRPC.LogPath)
	if err := os.MkdirAll(logDir, 0755); err != nil {
		return fmt.Errorf("failed to create log directory: %w", err)
	}

	// 启动 FRPC
	m.cmd = exec.Command(m.cfg.FRPC.Path, "-c", m.cfg.FRPC.ConfigPath)

	// 设置日志输出
	logFile, err := os.OpenFile(m.cfg.FRPC.LogPath, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0644)
	if err != nil {
		return fmt.Errorf("failed to open log file: %w", err)
	}
	m.cmd.Stdout = logFile
	m.cmd.Stderr = logFile

	if err := m.cmd.Start(); err != nil {
		return fmt.Errorf("failed to start frpc: %w", err)
	}

	m.running = true

	// 监控进程
	go m.monitor()

	log.Printf("FRPC started with PID %d", m.cmd.Process.Pid)
	return nil
}

// Stop 停止 FRPC
func (m *Manager) Stop() error {
	m.mu.Lock()
	defer m.mu.Unlock()

	if !m.running {
		return nil
	}

	// 发送停止信号
	close(m.stopCh)

	// 等待进程退出
	if m.cmd != nil && m.cmd.Process != nil {
		if err := m.cmd.Process.Kill(); err != nil {
			log.Printf("Failed to kill FRPC process: %v", err)
		}

		// 等待进程退出
		done := make(chan error, 1)
		go func() {
			done <- m.cmd.Wait()
		}()

		select {
		case <-done:
			// 进程已退出
		case <-time.After(5 * time.Second):
			// 超时
			log.Printf("FRPC process did not exit in time")
		}
	}

	m.running = false
	m.cmd = nil
	m.stopCh = make(chan struct{})

	log.Println("FRPC stopped")
	return nil
}

// Restart 重启 FRPC
func (m *Manager) Restart() error {
	if err := m.Stop(); err != nil {
		return err
	}

	// 等待一下再重启
	time.Sleep(time.Second)

	return m.Start()
}

// IsRunning 检查是否运行中
func (m *Manager) IsRunning() bool {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return m.running
}

// GetStatus 获取状态
func (m *Manager) GetStatus() Status {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return Status{
		Running: m.running,
	}
}

// StatusCh 获取状态通道
func (m *Manager) StatusCh() <-chan Status {
	return m.statusCh
}

// monitor 监控 FRPC 进程
func (m *Manager) monitor() {
	if m.cmd == nil {
		return
	}

	err := m.cmd.Wait()

	m.mu.Lock()
	m.running = false
	m.mu.Unlock()

	status := Status{
		Running: false,
	}

	if err != nil {
		status.Error = err.Error()
		log.Printf("FRPC exited with error: %v", err)
	} else {
		log.Println("FRPC exited normally")
	}

	// 发送状态
	select {
	case m.statusCh <- status:
	default:
	}
}

// GenerateConfig 生成 FRPC 配置文件
func GenerateConfig(cfg *config.Config, mappings []api.Mapping, serverAddr string) error {
	// 创建配置目录
	configDir := filepath.Dir(cfg.FRPC.ConfigPath)
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	// 生成配置内容
	content := generateConfigContent(mappings, serverAddr)

	// 写入临时文件
	tempPath := cfg.FRPC.ConfigPath + ".tmp"
	if err := os.WriteFile(tempPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write temp config: %w", err)
	}

	// 备份当前配置
	if _, err := os.Stat(cfg.FRPC.ConfigPath); err == nil {
		backupPath := cfg.FRPC.ConfigPath + ".backup"
		if err := copyFile(cfg.FRPC.ConfigPath, backupPath); err != nil {
			log.Printf("Failed to backup config: %v", err)
		}
	}

	// 原子替换
	if err := os.Rename(tempPath, cfg.FRPC.ConfigPath); err != nil {
		return fmt.Errorf("failed to replace config: %w", err)
	}

	return nil
}

// generateConfigContent 生成配置内容
func generateConfigContent(mappings []api.Mapping, serverAddr string) string {
	config := fmt.Sprintf(`# FRPC Configuration
# Generated by FRP Cloud Panel

serverAddr = "%s"
serverPort = 7000

[proxies]
`, serverAddr)

	for _, mapping := range mappings {
		if mapping.Status == "deleting" || mapping.Status == "disabled" {
			continue
		}

		switch mapping.Type {
		case "tcp":
			config += fmt.Sprintf(`
[[proxies]]
name = "%s"
type = "tcp"
localIP = "%s"
localPort = %d
remotePort = %d
`, mapping.Name, mapping.LocalIP, mapping.LocalPort, mapping.RemotePort)

		case "udp":
			config += fmt.Sprintf(`
[[proxies]]
name = "%s"
type = "udp"
localIP = "%s"
localPort = %d
remotePort = %d
`, mapping.Name, mapping.LocalIP, mapping.LocalPort, mapping.RemotePort)

		case "http":
			config += fmt.Sprintf(`
[[proxies]]
name = "%s"
type = "http"
localIP = "%s"
localPort = %d
`, mapping.Name, mapping.LocalIP, mapping.LocalPort)

			if mapping.Domain != "" {
				config += fmt.Sprintf(`customDomains = ["%s"]
`, mapping.Domain)
			}

		case "https":
			config += fmt.Sprintf(`
[[proxies]]
name = "%s"
type = "https"
localIP = "%s"
localPort = %d
`, mapping.Name, mapping.LocalIP, mapping.LocalPort)

			if mapping.Domain != "" {
				config += fmt.Sprintf(`customDomains = ["%s"]
`, mapping.Domain)
			}
		}
	}

	return config
}

// copyFile 复制文件
func copyFile(src, dst string) error {
	data, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	return os.WriteFile(dst, data, 0644)
}

// GenerateConfigContent 生成配置内容
func GenerateConfigContent(mappings []api.Mapping, serverAddr string) string {
	return generateConfigContent(mappings, serverAddr)
}

// CheckPort 检查本地端口是否可用
func CheckPort(port int) error {
	// TODO: 实现端口检查
	return nil
}
